### PR TITLE
Add blurred background

### PR DESCRIPTION
**Pull request by lenemter**
Closes https://github.com/elementary/greeter/pull/358
Closes https://github.com/elementary/greeter/pull/623

Background code was copied from Gala

### CODE REVIEW

**Comment by vjr** [comment]
I tried this branch and it works well for me, so thumbs up from my side. Hopefully this is reviewed/merged :-)

**Comment by vjr** [comment]
> I tried this branch and it works well for me, so thumbs up from my side. Hopefully this is reviewed/merged :-)

Scratch that! This PR seems to break/interfere with the "fade in" PR #697 recently merged. I was looking at a problem on my machine (with AMD RX580 GPU on OS 7.1 daily) with the fade-in being all noise/garbled but only the wallpaper/background, the other elements (ui_group) fade-in properly. I have not yet tested with OS8 ISO.

**Comment by lenemter** [comment]
@vjr Oops, I'll fix the fade-in animation as soon as I can

**Comment by danirabbit** [comment]
@vjr since we reverted the fade in for now, does this still break for you?

**Comment by vjr** [comment]
@danirabbit yes the blank screen issue is still present.

I just now tested on an updated os8 install showing greeter version `7.0.0 r1550 pkg96 daily ubuntu8.1`

Same issue after building and installing this branch so I don't think it was the fade-in PR so hopefully it will return in some form because it's cool.

My bad if I misguided y'all with my recent comments about the fadein causing artefacts which was occurring only on my older PC with an AMD RX 580 GPU.

**Comment by vjr** [comment]
Okay I just tested this branch with one change to move the `Gtk.init` call a few lines lower in `src/Application.vala` like was done in the fade in PR and it fixes the blank screen issue.

**Review by danirabbit — COMMENTED** [review]
A problem this introduces is now for light wallpapers the panel becomes illegible. So we probably need to also include everything for setting the panel for light or dark and probably sync the panel transparency setting for the user as well :sweat_smile:

**Comment by lenemter** [comment]
@danirabbit I fixed panel contrast here. I'll prepare a branch for syncing the transparency setting later

**Review by danirabbit — CHANGES_REQUESTED** [review]
Looks so good, couple of small things:

- [ ] It looks like the panel transition doesn't start until after the wallpaper transition completes. Is there a way to make this happen at the same time? Basically what I'm seeing is you switch cards, the wallpaper transition happens, then the panel transition happens.
- [ ] It looks like this is being set/updated when cards are switched, but it isn't set when the greeter first loads. So if the user that is focused when the greeter starts has a light wallpaper, the icons will be white until you focus another card and then switch back

**Review by danirabbit — APPROVED** [review]
LFG :rocket:

**Pull request merged**
