### PR TITLE
Nvidia drivers: Refresh background after suspend (#131)

### PR DESCRIPTION
**Pull request by jlnr**
Exactly the same fix as in https://github.com/elementary/gala/pull/330.

This should fix the first half of #131, but I don't have my Nvidia machine with me, so I can't test this myself right now.

### CODE REVIEW

**Comment by jlnr** [comment]
@leonardo-lemos Thanks for testing this PR! It turns out the greeter is not using `compositor/Wallpaper.vala` (like gala) but `src/Widgets/Wallpaper.vala` (for the crossfade effect). Consequently, calling `Meta.Background.refresh_all ()` did not fix the issue.

I've added code to have `PantheonGreeter` wait for resume events on Nvidia systems, but since `PantheonGreeter` does not have access to Mutter(?) (for the `gl_video_memory_purged` signal), I've had to use the OpenGL-based workaround that I just deleted in the compositor. Meh.

When a resume event on an Nvidia-based system is detected, I now call `wallpaper.reposition ()`, which seems to restore the wallpaper after resuming. However, the user list and clock are still garbled. I'm not sure why these use Clutter instead of Gtk, but no combination of `ensure_redraw` and `queue_redraw` seems to ungarble these widgets. They keep using purged textures.

One thing that almost works is to add `remove (clutter); add (clutter);` in `prepare_for_sleep`. But *sometimes* I ended up with a screen where both the users *and* the backgrounds where broken, so I've taken it out, even though it worked in 2 out of 3 attempts.

I don't have any more time to spend on this for this month. Maybe rewriting the user list & clock in pure Gtk would be easier? This, along with the changes in this PR, might be enough to fix the issue.

**Comment by jlnr** [comment]
@leonardo-lemos Thanks for the pointer. I won't stop anyone from finishing this PR, but I don't think I'll invest any more time here until #181 is merged.

Forgot to attach a photo I took of the current state of things – background works, user list is garbled.

img_3794

**Comment by jlnr** [comment]
I've removed my changes to the parts that have been rewritten in GTK. It's not a very simple fix, and should stop the dark grey background from corruption after resume (successfully tested here).

**Comment by jlnr** [comment]
I didn't have a lot of time for testing today, but I haven't seen any corruption on the master branch when resuming at the greeter. So I'm not sure if there's an actual issue left to fix here.

However, I have rebased this branch, and it seems to still be free of corruption, but with two changes:

* I've replaced the logind workaround with the more specific `gl_video_memory_purged` signal which was built precisely to recover OpenGL textures.
* I have made the `refresh` method on `Greeter.SystemBackground` static so that it can be called without creating a temporary dummy instance (which only refreshes the single, static `system_background` anyway).

**Comment by lvitals** [comment]
Okay, I did the tests, gl_video_memory_purged retrieves the OpenGL textures, and then the static update method is called to redo the color and the background image.

**Comment by leonardo-lemos** [comment]
I'm closing this PR since #206 and #208 supersede this.

**Pull request closed without merging**
