### PR TITLE
Add mouse navigation and password focus after keyboard navigation

### LINKED ISSUE #280: Focus password entry after every keyboard or mouse navigation
The password field is only focused when the greeter starts up and initial user is selected. If you switch users using keyboard left or right keys then the next user's password field is not auto selected, which it should be for convenience.

Similarly if mouse navigation (scroll up/down) is added then here too the password field should get auto focused after moving to the next user.

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/74696619-focus-password-entry-after-every-keyboard-or-mouse-navigation?utm_campaign=plugin&utm_content=tracker%2F60068889&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F60068889&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### LINKED ISSUE #281: Add mouse scroll up/down navigation to move to next user
Similar to what was on the "old" greeter, even though the user list moves left/right, the mouse scroll up or down should also move to the next user.

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/74696696-add-mouse-scroll-up-down-navigation-to-move-to-next-user?utm_campaign=plugin&utm_content=tracker%2F60068889&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F60068889&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by vjr**
* Focus password field after keyboard left/right navigation
* Add mouse scroll up/down navigation to select next user

fixes #280 and fixes #281

### CODE REVIEW

**Comment by vjr** [comment]
At the moment nothing happens when I scroll the mouse - can anyone take a look why?

Also, with password focus after keyboard left/right navigation, there is a audible event alert (thunk sound) every time I switch to the next user back and forth.

**Comment by vjr** [comment]
OK got the mouse scrolling to work with https://github.com/elementary/greeter/pull/282/commits/e4848ad230091b1bcbc67f1434b23678872f1f68

Do I need to be checking for text direction (RTL versus LTR) to switch the scroll direction, like is done for the keyboard left/right navigation?

**Comment by vjr** [comment]
OK I seemed to have fixed the audible event alert thunk sound too in https://github.com/elementary/greeter/pull/282/commits/8a3fafbad124550c4e48dc3a27e24182ffdc594d

**Comment by danrabbit** [comment]
Can you split this into two branches please? In general a branch should not combine unrelated concerns

**Comment by vjr** [comment]
I've created two separate PRs #284 and #285 so closing this one.

**Pull request closed without merging**
