### PR TITLE
Blurred Pixbuf on Clutter Canvas

### PR DESCRIPTION
**Pull request by torikulhabib**
Another way to paint picture blurred on stage

### CODE REVIEW

**Comment by torikulhabib** [comment]
im sorry, my monitor was broken.
IMG20210815150741

**Comment by candiedoperation** [comment]
I've Published a Demo of this PR on YouTube

[Odin Greeter Blur PR Demo](https://youtu.be/gJoxzFUPOoE "Blur PR Demo - Click to Watch")

**Comment by vjr** [comment]
This looks very nice already!

Couple of comments/requests...

1. Would it look nicer to blur the wallpaper background even more so that you can barely see what it is?
2. Possible to add some sort of "crossfade" between wallpapers when switching users?

**Comment by torikulhabib** [comment]
@vjr Oke!!!
i will fix soon

**Pull request closed without merging**
