### PR TITLE
Add button to open terminal

### PR DESCRIPTION
**Pull request by meisenzahl**
Closes https://github.com/elementary/greeter/issues/497

### CODE REVIEW

**Comment by meisenzahl** [comment]
Adds a button that should open a terminal when clicked. Unfortunately, the terminal does not open at the moment.

Bildschirmfoto von 2021-01-17 08 02 27

@danrabbit I copied your code to open `io.elementary.initial-setup` and adapted it so that `io.elementary.terminal` should be started. Unfortunately this does not work. Do you remember if you had problems back then and had to configure something special for `io.elementary.initial-setup`?

**Comment by hanaral** [comment]
This is supposed to be an OSusable by anyone, adding a big ass terminal button to the bottom of the login screen is asking for trouble. How about making it a specific keybind instead?

**Comment by meisenzahl** [comment]
Currently it is in the style of the other buttons like "Log in as Guest" and "Manual Login...". I am not sure what the final design will look like. But we already have keybindings to open a terminal `Ctrl+Alt+F1-F6`. So I think a button, in whatever form, makes sense.

But I'm not the right one to decide that, so I'm looking forward to feedback from @elementary/ux.

**Comment by cassidyjames** [comment]
I'm really :-1: on adding a way to open Terminal from the greeter; that seems like an invitation to way too much trouble. For extreme recovery needs (like a non-launching session), there is already recovery mode when booting and the TTY.

**Pull request closed without merging**
