### PR TITLE
Adapt to the latest Mutter API

### PR DESCRIPTION
**Pull request by worldofpeace**
I've tested that it builds with mutter 3.34.1 and 3.28.4.
What I've done in `SystemBackground.vala` is probably totally incorrect. A suggestion is welcome on what we actually should be doing.

What I've done is adapted the changes in https://github.com/elementary/gala/pull/566, as it's literally the code copy pasted mostly, to be used here.

Fixes https://github.com/elementary/greeter/issues/120.

It would be fabulous :v: if we could have everything adapted to latest mutter before the end of the year.

### CODE REVIEW

**Comment by Tireg** [comment]
Ok now I can confirm this works great since May 8, when I dropped the first patch (https://github.com/elementary/greeter/issues/120#issuecomment-490663451).
Didn't encountered any issue from this time with greeter.
@worldofpeace has done a great work by adding this PR and adapting changes for newer mutter versions.

This would be great to have some review here as everything seems to work as expected.

**Comment by worldofpeace** [comment]
> Ok now I can confirm this works great since May 8, when I dropped the first patch ([#120 (comment)](https://github.com/elementary/greeter/issues/120#issuecomment-490663451)).
> Didn't encountered any issue from this time with greeter.
> @worldofpeace has done a great work by adding this PR and adapting changes for newer mutter versions.
> 
> This would be great to have some review here as everything seems to work as expected.

Thanks @Tireg, also thanks for tracking down all the issues so carefully in gala.
It's pretty important to me as a downstream to be able to support latest mutter API's and not hold compatibility packages.

**Comment by worldofpeace** [comment]
@tintou I did notice that the background with mutter 3.34 never got drawn...

**Comment by worldofpeace** [comment]
Will quote that
> What I've done in SystemBackground.vala is probably totally incorrect. A suggestion is welcome on what we actually should be doing.

I believe there's something going on there.

**Comment by tintou** [comment]
@worldofpeace I just pushed a fix to this, It was because `system_background.set_wallpaper ();` wasn't called in the 3.34 version, I fixed it by setting the system wallpaper at object construction as it is done in Gala

**Comment by worldofpeace** [comment]
> @worldofpeace I just pushed a fix to this, It was because `system_background.set_wallpaper ();` wasn't called in the 3.34 version, I fixed it by setting the system wallpaper at object construction as it is done in Gala

Thanks :sparkles:

**Comment by tintou** [comment]
Thank you :)

**Comment by worldofpeace** [comment]
I'm not sure if https://github.com/elementary/gala/issues/518 will also be present in the greeter. But if any fix makes its way there it probably should be ported here too.

**Pull request merged**
