### PR TITLE
Spelling: Occurred

### PR DESCRIPTION
**Pull request by comradekingu**
https://en.wiktionary.org/wiki/occurred
Spotted by @Sporiff on Weblate

### CODE REVIEW

**Comment by cassidyjames** [comment]
This looks like it needs to match an error coming from fprintd, so if there's a typo there, we'd have to match it.

**Comment by comradekingu** [comment]
@cassidyjames As per https://github.com/dsd/fprintd/pull/4/files ?

**Comment by cassidyjames** [comment]
@comradekingu indeed!

**Comment by leonardo-lemos** [comment]
Blocked until fprintd/pull/4 is merged.

**Comment by tintou** [comment]
Note that the string change has been merged a while ago in https://gitlab.freedesktop.org/libfprint/fprintd/commit/51f4dce4e778bcce18659aa1d8a22a4d1cfdbd1f (the right repository for fprintd)

**Pull request closed without merging**
