### PR TITLE
Update README to with meson

### LINKED ISSUE #135: Update README to with meson

### PR DESCRIPTION
**Pull request by ryonakano**
Fix #135

This PR is ready to review.

### CODE REVIEW

**Comment by arshubham** [comment]
@ryonakano I seems some dependencies are not listed too. Can't compile with the listed ones.

compositor/meson.build:7:0: ERROR:  Native dependency 'gnome-desktop-3.0' not found

**Comment by arshubham** [comment]
@ryonakano you forgot to add meson as dependency

**Comment by danrabbit** [comment]
Thanks for fixing this!

**Comment by ryonakano** [comment]
Thank you @arshubham & @danrabbit!!

**Pull request merged**
