### PR TITLE
Meson: correct install_path

### PR DESCRIPTION
**Pull request by worldofpeace**
This has been the correct way since meson 0.37.

### CODE REVIEW

**Comment by worldofpeace** [comment]
Yeah also just noticed that this isn't the only occurrence of this so I'll fix the rest of them.

**Comment by worldofpeace** [comment]
@codygarver There's no `meson_version : ' '` in 
https://github.com/elementary/greeter/blob/25584773f84d10093defaa014883fba93f2d66eb/meson.build#L1

**Comment by codygarver** [comment]
@worldofpeace then it should be added

**Comment by worldofpeace** [comment]
:fireworks: :sparkles:

**Pull request merged**
