### PR TITLE
Add Mutter 47 support

### LINKED ISSUE #744: add support for mutter 47 / libmutter-15
With mutter 47.alpha, the library name changed again, to libmutter-15.

### PR DESCRIPTION
**Pull request by danirabbit**
Fixes #744 

Can rebase merge if desired

### CODE REVIEW

**Comment by stsdc** [comment]
So many ifs... Are there concepts of a plan to drop them in the future?

**Comment by danirabbit** [comment]
We can probably drop support for Mutter <= 13 since we're not releasing to Jammy anymore, but I think that should be proposed in another branch

**Comment by danirabbit** [comment]
Actually looks like[ Gentoo is still using 13](https://github.com/elementary/wingpanel/issues/570), so maybe 12? Will need input from others

**Comment by bobby285271** [comment]
For NixOS, we pin Mutter to 43 but we definitely will unpin and bump to 46 when we bump gala to 8.x so this is not an issue for NixOS. I previously made a small script in https://github.com/elementary/gala/pull/1496 's PR description that can semi (since it requires e.g. [taking care `#elif` manually](https://github.com/elementary/gala/pull/1496/commits/845361275a215894e2a0407484cde782c75242e6)) automatically clean up these ifs.

**Comment by stsdc** [comment]
Do we have a list of distros that we want to support?

**Comment by danirabbit** [comment]
@stsdc I don't think so. But either way I think that's outside of the scope of this PR. I'm just trying to unbreak Fedora here 😅

**Comment by stsdc** [comment]
I think it is ok to merge this and immediately prepare a draft PR that will remove `#if` blocks when the newer Mutter version will arrive in Fedora.

**Review by stsdc — APPROVED** [review]

**Pull request merged**
