### PR TITLE
Apply AccountsService power settings to lightdm user

### LINKED ISSUE #161: Greeter does not respect power saving settings
Noticed, although I disabled any power savings in System Settings->Power...
screenshot from 2018-09-28 19 25 36 2x
...that Greeter suspends my machine after some time period. Don't know the exact time period, but the machine gets suspended.

I'm pretty sure, LOKI didn't suspend my PC while locked.
Please take a look into this. If this is by design, please remember that not every user likes to suspend his machine, thus please provide an option to switch it off.

My system:
```
System:    Host: elementary-os-beta2 Kernel: 4.15.0-34-generic x86_64 bits: 64 compiler: gcc v: 7.3.0 
           Desktop: Pantheon Distro: elementary OS 5.0 Juno base: Ubuntu 18.04 bionic 
Machine:   Type: Desktop Mobo: ASUSTeK model: Z170-DELUXE v: Rev 1.xx serial: <filter> 
           UEFI [Legacy]: American Megatrends v: 3504 date: 06/29/2017 
CPU:       Topology: Quad Core model: Intel Core i7-6700K bits: 64 type: MT MCP arch: Skylake-S rev: 3 
           L2 cache: 8192 KiB 
           flags: lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx bogomips: 64128 
           Speed: 800 MHz min/max: 800/4300 MHz Core speeds (MHz): 1: 800 2: 800 3: 800 4: 801 5: 800 6: 800 
           7: 801 8: 800 
Graphics:  Device-1: NVIDIA GP104 [GeForce GTX 1080] driver: nvidia v: 390.48 bus ID: 01:00.0 
           Display: x11 server: X.Org 1.19.6 driver: nvidia unloaded: fbdev,modesetting,nouveau,vesa 
           resolution: 3840x2160~60Hz 
           OpenGL: renderer: GeForce GTX 1080/PCIe/SSE2 v: 4.6.0 NVIDIA 390.48 direct render: Yes 
Audio:     Device-1: Intel Sunrise Point-H HD Audio driver: snd_hda_intel v: kernel bus ID: 00:1f.3 
           Device-2: NVIDIA GP104 High Definition Audio driver: snd_hda_intel v: kernel bus ID: 01:00.1 
           Sound Server: ALSA v: k4.15.0-34-generic 
Network:   Device-1: Intel Ethernet I219-V driver: e1000e v: 3.2.6-k port: f000 bus ID: 00:1f.6 
           IF: enp0s31f6 state: up speed: 1000 Mbps duplex: full mac: <filter> 
           Device-2: Broadcom Limited BCM4360 802.11ac Wireless Network Adapter driver: bcma-pci-bridge v: N/A 
           port: e000 bus ID: 07:00.0 
           Device-3: Intel I211 Gigabit Network driver: igb v: 5.4.0-k port: c000 bus ID: 0b:00.0 
           IF: enp11s0 state: down mac: <filter> 
Drives:    Local Storage: total: 2.34 TiB used: 35.86 GiB (1.5%) 
           ID-1: /dev/sda vendor: Samsung model: SSD 850 PRO 256GB size: 238.47 GiB 
           ID-2: /dev/sdb vendor: Samsung model: SSD 850 PRO 1TB size: 953.87 GiB 
           ID-3: /dev/sdc vendor: Crucial model: CT1050MX300SSD1 size: 978.09 GiB 
           ID-4: /dev/sdd vendor: Kingston model: SH100S3120G size: 111.79 GiB 
           ID-5: /dev/sde vendor: Kingston model: SV300S37A120G size: 111.79 GiB 
Partition: ID-1: / size: 109.53 GiB used: 35.86 GiB (32.7%) fs: ext4 dev: /dev/sde1 
Sensors:   System Temperatures: cpu: 36.0 C mobo: N/A gpu: nvidia temp: 54 C 
           Fan Speeds (RPM): cpu: 0 gpu: nvidia fan: 0% 
Info:      Processes: 254 Uptime: 12m Memory: 31.35 GiB used: 1.42 GiB (4.5%) Init: systemd runlevel: 5 
           Compilers: gcc: 7.3.0 Shell: bash v: 4.4.19 inxi: 3.0.25
```

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/64015923-greeter-does-not-respect-power-saving-settings?utm_campaign=plugin&utm_content=tracker%2F60068889&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F60068889&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by davidmhewitt**
Fixes #161 

Requires https://github.com/elementary/default-settings/pull/134

Works in conjunction with https://github.com/elementary/switchboard-plug-power/pull/123 to allow the user to set the suspend settings for the greeter.

### CODE REVIEW

**Comment by kgrubb** [comment]
Alright I tested this out via doing the following:

1. Update your `/usr/share/accountsservice/interfaces/io.elementary.pantheon.AccountsService.xml` withe changes here: https://github.com/elementary/default-settings/pull/134

1. Pull in this branch for greeter and the following branch for switchbpard-plug-power: https://github.com/elementary/switchboard-plug-power/pull/123

1. Build and install greeter & switchboard-plug-power

1. Make a change to your power settings here:
Screenshot from 2019-09-18 15-42-43

	For example, change the suspend option to 5 minutes.

1. wait for an eternity (5 minutes lol)

1. observe things working properly with greeter when you wake from suspend!

For observing the output, I used d-feet. Here's the new properties:
Screenshot from 2019-09-18 15-45-19

**Comment by kgrubb** [comment]
Alright, just coming back to report that this seems to resolve the issue where greeter would still suspend even if the option was set to `never`.

**Comment by danrabbit** [comment]
Sounds like after some discussion in Slack that we want to make sure the behavior here is not the currently selected user but the last logged in user. This way settings can't be accidentally changed by just selecting another user (which could be done by accident or by anyone else with access to the lock screen)

**Comment by kgrubb** [comment]
Alright, the latest change to this branch is working with last-used.

What I did:
1. login as one user & set suspend to 5 minutes
2. log out
3. log in to next user & set suspend to never
4. wait for the session to fallback to the greeter and confirm suspend doesn't happen after 5 minutes
5. change focus to the other user card and wait 5 minutes to confirm suspend also doesn't happen there either.

the same flow also works if i skip step 2 and just swap logged in accounts.

**Comment by jtrees** [comment]
When will this be released?

**Comment by kgrubb** [comment]
Hey @jtrees, this was released as part of version 5.0.2

**Comment by jtrees** [comment]
Huh, ok. Well it doesn't fix #161 for me.

**Comment by davidmhewitt** [comment]
@jtrees If I remember correctly, it won't take effect immediately as the new switchboard code will only push the settings to AccountsService when they're changed. So you'll need to go into switchboard and change the settings to something else and then back to what you want them to be before they should take effect.

**Comment by jtrees** [comment]
> @jtrees If I remember correctly, it won't take effect immediately as the new switchboard code will only push the settings to AccountsService when they're changed. So you'll need to go into switchboard and change the settings to something else and then back to what you want them to be before they should take effect.

Yeah, I did that. Still doesn't work.

**Comment by lmam0000** [comment]
I can confirm that this issue is still not resolved. Every day I have perform the magic incantation as the lightdm user to change from 'suspend' to 'nothing'

**Comment by mroi** [comment]
Are these settings only applied within greeter _after_ the first user has successfully logged in? If so, maybe this is confusing some people?

I do not suggest to change this behavior, I just want to clarify, why this PR does not solve the issue for some people.

**Comment by chinarut** [comment]
I still have this issue in 7.1.  after poking around StackExchange quite a bit - I found a link to this merge and the suggested workarounds are not working:

```
root@improv:~# su - -s /bin/bash lightdm
lightdm@improv:~$ dbus-launch gsettings get org.gnome.settings-daemon.plugins.power sleep-inactive-ac-type
'suspend'
lightdm@improv:~$ dbus-launch gsettings set org.gnome.settings-daemon.plugins.power sleep-inactive-ac-type nothing
lightdm@improv:~$ dbus-launch gsettings get org.gnome.settings-daemon.plugins.power sleep-inactive-ac-type
'nothing'
lightdm@improv:~$ exit
root@improv:~# reboot
```

after reboot - setting is back to suspend after 1200s:

```
lightdm@improv:~$ dbus-launch gsettings get org.gnome.settings-daemon.plugins.power sleep-inactive-ac-type
'suspend'
lightdm@improv:~$ dbus-launch gsettings get org.gnome.settings-daemon.plugins.power sleep-inactive-ac-timeout
1200
```

tried doing the above twice (including rebooting twice), the setting won’t stick as the `lightdm` user.

could someone confirm this is indeed the same issue as discussed here?

**Pull request merged**
