### PR TITLE
Delete io.elementary.greeter.whitelist

### LINKED ISSUE #449: deb-packaging: rename io.elementary.greeter.whitelist -> io.elementary.greeter.allowed
## Prerequisites
- [ ] I have searched open and closed issues for duplicates.

## Describe the bug
The old working has been deprecated https://github.com/elementary/wingpanel/pull/326 @tintou 

Another question I have is, is this file required and why isn't it installed by meson. In downstreams I see them having to ship this separately.

### PR DESCRIPTION
**Pull request by danrabbit**
Fixes #449 

This should probably not be needed anymore since indicators know whether they're running in session or not and adapt accordingly

### CODE REVIEW

**Comment by worldofpeace** [comment]
I tried this in nixos, and it seems the datetime indicator now shows
Screenshot from 2020-07-07 16 56 26

**Comment by worldofpeace** [comment]
datetime version 2.2.5

**Comment by danrabbit** [comment]
@worldofpeace can you open an issue against the datetime indicator? We should probably fix it there

**Comment by worldofpeace** [comment]
> @worldofpeace can you open an issue against the datetime indicator? We should probably fix it there

Absolutely, thanks for asking.

**Pull request merged**
