### PR TITLE
MainWindow: Select a session when no previous selection exists

### LINKED ISSUE #212: Greeter knows no session and crashes
On fedora 28, 29, and 30, a greeter built from the latest git master crashes after successfully authenticating with password:

```
(...) session_real_run: assertion 'priv->argv != NULL' failed

Process 952 (io.elementary.g) of user 977 dumped core.
    Stack trace of thread 952:
    #0  0x00007f53689b9855 _g_log_abort (libglib-2.0.so.0)
    #1  0x00007f53689ba921 g_log_default_handler (libglib-2.0.so.0)
    #2  0x00007f53689bab6f g_logv (libglib-2.0.so.0)
    #3  0x00007f53689bad63 g_log (libglib-2.0.so.0)
    #4  0x00005591cc9a935b _greeter_main_window_authentication_complete_lightdm_greeter_authentication_complete (io.elementary.greeter)
    #5  0x00007f5368c8eee6 _g_closure_invoke_va (libgobject-2.0.so.0)
    #6  0x00007f5368cab361 g_signal_emit_valist (libgobject-2.0.so.0)
    #7  0x00007f5368cab903 g_signal_emit (libgobject-2.0.so.0)
    #8  0x00007f5366d039d4 handle_message (liblightdm-gobject-1.so.0)
    #9  0x00007f5366d03bd1 from_server_cb (liblightdm-gobject-1.so.0)
    #10 0x00007f53689b388d g_main_context_dispatch (libglib-2.0.so.0)
    #11 0x00007f53689b3c58 g_main_context_iterate.isra.21 (libglib-2.0.so.0)
    #12 0x00007f53689b3f82 g_main_loop_run (libglib-2.0.so.0)
    #13 0x00007f53682877fd gtk_main (libgtk-3.so.0)
    #14 0x00005591cc9a7ae0 _vala_main (io.elementary.greeter)
    #15 0x00007f536673f11b __libc_start_main (libc.so.6)
    #16 0x00005591cc9a773a _start (io.elementary.greeter)

(... other unrelated threads following ...)
```

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/66569115-greeter-knows-no-session-and-crashes?utm_campaign=plugin&utm_content=tracker%2F60068889&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F60068889&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by danrabbit**
fixes #212 

When the selection is "" grab the first value in the dict

### CODE REVIEW

**Comment by decathorpe** [comment]
By the way, is this only a stop-gap measure until the last selected session is remembered?

**Comment by worldofpeace** [comment]
Also, how is a last selected session that no longer exists handled?

**Comment by danrabbit** [comment]
@decathorpe it should remember what the last selected session was already. It should only be "" on a clean system

@worldofpeace I guess it isn't handled currently

**Comment by decathorpe** [comment]
It *definitely* doesn't remember the last selection on fedora. On my test install, I have to remember to check "Pantheon" **each time I log in**, otherwise the greeter crashes.

**Pull request closed without merging**
